---
- name: Cockpit
  hosts: containerhosts
  become: yes
  roles:
    - linux-system-roles.cockpit
  vars:
    cockpit_packages:
      - cockpit-pcp
      - cockpit-podman
      - cockpit-system
      - cockpit-ws
