---
- name: Node-RED
  hosts: containerhosts
  vars:
    docker_hub_username: "{{ lookup('env', 'DOCKER_HUB_USERNAME') }}"
    docker_hub_token: "{{ lookup('env', 'DOCKER_HUB_TOKEN') }}"
    docker_hub_image: "docker.io/nodered/node-red:2.1.4-1"
  roles:
    - role: podman_node_red
