---
- name: update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: ensure Podman is installed
  ansible.builtin.apt:
    name: podman
    state: latest

- name: ensure podman-docker is installed
  ansible.builtin.apt:
    name: podman-docker
    state: latest
