---
- name: update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: be sure curl is installed
  ansible.builtin.apt:
    name: curl
    state: present
  tags: tooling

# Needed for Cockpit monitoring
- name: be sure pcp is installed
  ansible.builtin.apt:
    name: pcp
    state: present
  tags: tooling

- name: be sure tmux is installed
  ansible.builtin.apt:
    name: tmux
    state: present
  tags: tooling

- name: be sure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present
  tags: security

- name: be sure fail2ban is installed
  ansible.builtin.apt:
    name: fail2ban
    state: present
  tags: security
