---
- name: allow SSH through UFW
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp
    log: yes
  tags:
    - ufw

- name: allow Cockpit through UFW
  community.general.ufw:
    rule: allow
    port: 9090
    proto: tcp
    log: yes
  tags:
    - ufw

- name: allow mDNS through UFW
  community.general.ufw:
    rule: allow
    to_ip: 224.0.0.251
    proto: igmp
    log: no
  tags:
    - ufw

- name: drop multicast without logging
  community.general.ufw:
    rule: deny
    to_ip: 224.0.0.1
    log: no
  tags:
    - ufw

- name: set default incoming UFW policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny
  tags:
    - ufw

- name: set default outgoing UFW policy to allow
  community.general.ufw:
    direction: outgoing
    policy: allow
  tags:
    - ufw

- name: enable UFW
  community.general.ufw:
    state: enabled
    logging: on
  tags:
    - ufw
